### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by CoreyH** [travisvn/gptree#1]
Does it work on Windows?

**Comment by CoreyH** [comment]
Got it working. 

I had to:
```
pip install pyreadline3 # For readline support
pip install windows-curses # For curses support
```

**Comment by travisvn** [comment]
@CoreyH I'm glad you were able to get it working! 

It's not in the `README`, but did you try the `.exe` file under the `Releases` section? https://github.com/travisvn/gptree/releases 

Command line tools (or any terminal interface) on Windows is... 😵‍💫 I'd probably opt for `wsl`, but I don't know. 

Not having a Unix terminal was probably my biggest complaint while working at Microsoft 😅

**Comment by CoreyH** [comment]
a) the exe wasn't available when I first discovered this project I don't think. 

b) The new terminal from MS is pretty nice, although I am jealous of Mac/Linux users getting the newest stuff like Warp. 

c) I got a Windows Defender warning ![image](https://github.com/user-attachments/assets/b908bb31-9eb9-45e8-9b0c-b76fccc5507a) and can't download it.
